spring:
  application:
    name: registrioApi

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=registro;trustServerCertificate=true
    username: sa
    password: DISICOMP2024
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
