spring:
  application:
    name: registrioApi

  datasource:
    url: jdbc:sqlserver://VMI528457\\SQLEXPRESS;databaseName=registro;encrypt=false
    username: sa
    password: Esc0bar2485$$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
